name: ci

on:
  push:
    branches:
      - antonpirker/test-gh-workflows

  pull_request:

jobs:
  dist:
    name: Build Layer Directory
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - run: |
          mkdir dist
          mkdir dist/sentry-lambda-layer
          mkdir dist/sentry-lambda-layer/python
          echo "something" > dist/sentry-lambda-layer/python/bla.txt
          echo "not enought stuff?" > dist/sentry-lambda-layer/main.txt

      # make dist
      # make lambda-layer-dir (new)
      # make add-extension-binaries (new)
      # make lambda-distribution-zip (new)

      - uses: actions/upload-artifact@v2
        with:
          name: prepared-lambda-layer-${{ github.sha }}
          path: |
            dist/*

      - uses: getsentry/action-build-aws-lambda-extension@v1
        with:
          artifact_name: prepared-lambda-layer-${{ github.sha }}
