name: ci

on:
  push:
    branches:
      - antonpirker/test-gh-workflows

  pull_request:

jobs:
  dist:
    name: Build Layer Directory
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - run: |
          mkdir dist
          mkdir dist/sentry-lambda-layer
          mkdir dist/sentry-lambda-layer/python
          echo "something" > dist/sentry-lambda-layer/python/bla.txt
          echo "not enought stuff?" > dist/sentry-lambda-layer/main.txt

      # make dist
      # make lambda-layer-dir (new)
      # make add-extension-binaries (new)
      # make lambda-distribution-zip (new)

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ github.sha }}
          path: |
            dist/*

  extension:
    name: Build extions package
    runs-on: ubuntu-latest
    needs: dist

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: ${{ github.sha }}
      - run: |
          ls -alh
          mkdir sentry-lambda-layer/extensions
          echo "pwd $$ ls -alh" > sentry-lambda-layer/extensions/my-extension.sh
          chmod +x sentry-lambda-layer/extensions/my-extension.sh
          curl -0 --output sentry-lambda-layer/relay `curl -s https://release-registry.services.sentry.io/apps/relay/latest | jq -r .files.\"relay-Linux-x86_64\".url`

      - run: |
          zip -r sentry-lambda-layer.zip sentry-lambda-layer/
          ls -alh
          echo "im zip"
          unzip -Z1 sentry-lambda-layer.zip
